os: windows
language: csharp
solution: NitrControlPanel.sln
mono: none

before_install:
- powershell choco install nuget.commandline
- powershell choco install visualstudio2019buildtools
- powershell Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -Proxy $env:HTTP_PROXY -ProxyUseDefaultCredentials -OutFile 'dotnet-install.ps1';
- powershell ./dotnet-install.ps1 -InstallDir '~/.dotnet' -Version '3.0.0' -ProxyAddress $env:HTTP_PROXY -ProxyUseDefaultCredentials;
- powershell refreshenv
- powershell dotnet --list-sdks

install:
- nuget restore NitrControlPanel.sln
script:
  - msbuild /t:Restore
  - msbuild /p:Configuration=Release

deploy:
  edge: true
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    repo: bitcav/Nitr-Control-Panel
    branches:    
      only:      
      - master 
  skip_cleanup: true

  draft: true

