os: windows
language: csharp
solution: NitrControlPanel.sln
mono: none

before_install:
- powershell choco install nuget.commandline
- powershell choco install visualstudio2019buildtools
- powershell choco upgrade dotnetcore-sdk
- powershell choco upgrade dotnetcore
- powershell refreshenv


script:
- bash deploy.sh
- ls NitrControlPanel
- ls NitrControlPanel/bin
- ls NitrControlPanel/bin/Release
- ls NitrControlPanel/Publish

deploy:
  edge: true
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    repo: bitcav/Nitr-Control-Panel
    branches:    
      only:      
      - master 
  skip_cleanup: true
  file:
  - NitrControlPanel/bin/Release/NitrControlPanel.exe

  draft: true

