os: windows
language: csharp
solution: NitrControlPanel.sln
mono: none

before_install:
- choco install nuget.commandline --pre 
- choco install dotnetcore-sdk --version 3.1.107 --pre
install:
- nuget restore NitrControlPanel.sln
script:
  - msbuild /t:Restore
  - msbuild /p:Configuration=Release

deploy:
  edge: true
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    repo: bitcav/Nitr-Control-Panel
    branches:    
      only:      
      - master 
  skip_cleanup: true

  draft: true

